# Generated by Django 2.2.6 on 2019-10-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='The test of the content', max_length=255),
        ),
    ]
